### ISSUE TITLE
Tentative Support for Mixins

### ISSUE THREAD

**Issue by shadowrylander** [cjrh/autoslot#4]
Hello!
&nbsp;&nbsp;&nbsp;&nbsp; I'm assuming that any problems occurring with `mixins` may not be solved by this, correct? Including the "instance lay-out" error?
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by cjrh** [comment]
That is correct:

```
from autoslot import Slots

class B(Slots):
    def __init__(self):
        self.a = 1
        self.b = 2

class C(Slots):
    def __init__(self):
        self.a = 3
        self.b = 4

class D(B, C):
    pass


d = D()
print(d)
```

Output:

```
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    class D(B, C):
  File "C:\Users\caleb\temp\autoslotmixin\venv\lib\site-packages\autoslot.py", line 50, in __new__
    return super().__new__(mcs, name, bases, ns)
TypeError: multiple bases have instance lay-out conflict
Press any key to continue . . .
```

**Comment by shadowrylander** [comment]
Well, that's unfortunate. Thank you kindly for the help, anyway!
